---
- name: Sudo installed
  action: >
    {{ ansible_pkg_mgr }}
    name='sudo'
    state='present'


- name: Add sudoers NOPASSWD for users
  lineinfile:
    path: '/etc/sudoers.d/{{ item.name }}'
    state: present
    create: yes
    line: "{{ item.name + ' ALL=(ALL) NOPASSWD: ALL' }}"
    owner: 'root'
    group: 'root'
    mode: '0600'
    validate: /usr/sbin/visudo -cf %s
  with_items: "{{ users }}"
  when: >
    item.sudo_nopasswd is defined and
    item.sudo_nopasswd == true